// Code generated by 'go generate'; DO NOT EDIT.

package hwkey

import (
	"syscall"
	"unsafe"

	"golang.org/x/sys/windows"
)

var _ unsafe.Pointer

// Do the interface allocations only once for common
// Errno values.
const (
	errnoERROR_IO_PENDING = 997
)

var (
	errERROR_IO_PENDING error = syscall.Errno(errnoERROR_IO_PENDING)
	errERROR_EINVAL     error = syscall.EINVAL
)

// errnoErr returns common boxed Errno values, to prevent
// allocations at runtime.
func errnoErr(e syscall.Errno) error {
	switch e {
	case 0:
		return errERROR_EINVAL
	case errnoERROR_IO_PENDING:
		return errERROR_IO_PENDING
	}
	// TODO: add more here, after collecting data on the common
	// error values see on Windows. (perhaps when running
	// all.bat?)
	return e
}

var (
	modncrypt = windows.NewLazySystemDLL("ncrypt.dll")

	procNCryptCreatePersistedKey  = modncrypt.NewProc("NCryptCreatePersistedKey")
	procNCryptDeleteKey           = modncrypt.NewProc("NCryptDeleteKey")
	procNCryptExportKey           = modncrypt.NewProc("NCryptExportKey")
	procNCryptFinalizeKey         = modncrypt.NewProc("NCryptFinalizeKey")
	procNCryptFreeObject          = modncrypt.NewProc("NCryptFreeObject")
	procNCryptOpenKey             = modncrypt.NewProc("NCryptOpenKey")
	procNCryptOpenStorageProvider = modncrypt.NewProc("NCryptOpenStorageProvider")
	procNCryptSetProperty         = modncrypt.NewProc("NCryptSetProperty")
	procNCryptSignHash            = modncrypt.NewProc("NCryptSignHash")
)

func nCryptCreatePersistedKey(hProvider nCryptProvHandle, phKey *nCryptKeyHandle, pszAlgId *uint16, pszKeyName *uint16, dwLegacyKeySpec uint32, dwFlags uint32) (ret uint32) {
	r0, _, _ := syscall.SyscallN(procNCryptCreatePersistedKey.Addr(), uintptr(hProvider), uintptr(unsafe.Pointer(phKey)), uintptr(unsafe.Pointer(pszAlgId)), uintptr(unsafe.Pointer(pszKeyName)), uintptr(dwLegacyKeySpec), uintptr(dwFlags))
	ret = uint32(r0)
	return
}

func nCryptDeleteKey(hKey nCryptKeyHandle, dwFlags uint32) (ret uint32) {
	r0, _, _ := syscall.SyscallN(procNCryptDeleteKey.Addr(), uintptr(hKey), uintptr(dwFlags))
	ret = uint32(r0)
	return
}

func nCryptExportKey(hKey nCryptKeyHandle, hExportKey nCryptKeyHandle, pszBlobType *uint16, pParameterList *byte, pbOutput *byte, cbOutput uint32, pcbResult *uint32, dwFlags uint32) (ret uint32) {
	r0, _, _ := syscall.SyscallN(procNCryptExportKey.Addr(), uintptr(hKey), uintptr(hExportKey), uintptr(unsafe.Pointer(pszBlobType)), uintptr(unsafe.Pointer(pParameterList)), uintptr(unsafe.Pointer(pbOutput)), uintptr(cbOutput), uintptr(unsafe.Pointer(pcbResult)), uintptr(dwFlags))
	ret = uint32(r0)
	return
}

func nCryptFinalizeKey(hKey nCryptKeyHandle, dwFlags uint32) (ret uint32) {
	r0, _, _ := syscall.SyscallN(procNCryptFinalizeKey.Addr(), uintptr(hKey), uintptr(dwFlags))
	ret = uint32(r0)
	return
}

func nCryptFreeObject(hObject uintptr) (ret uint32) {
	r0, _, _ := syscall.SyscallN(procNCryptFreeObject.Addr(), uintptr(hObject))
	ret = uint32(r0)
	return
}

func nCryptOpenKey(hProvider nCryptProvHandle, phKey *nCryptKeyHandle, pszKeyName *uint16, dwLegacyKeySpec uint32, dwFlags uint32) (ret uint32) {
	r0, _, _ := syscall.SyscallN(procNCryptOpenKey.Addr(), uintptr(hProvider), uintptr(unsafe.Pointer(phKey)), uintptr(unsafe.Pointer(pszKeyName)), uintptr(dwLegacyKeySpec), uintptr(dwFlags))
	ret = uint32(r0)
	return
}

func nCryptOpenStorageProvider(phProvider *nCryptProvHandle, pszProviderName *uint16, dwFlags uint32) (ret uint32) {
	r0, _, _ := syscall.SyscallN(procNCryptOpenStorageProvider.Addr(), uintptr(unsafe.Pointer(phProvider)), uintptr(unsafe.Pointer(pszProviderName)), uintptr(dwFlags))
	ret = uint32(r0)
	return
}

func nCryptSetProperty(hObject nCryptKeyHandle, pszProperty *uint16, pbInput *byte, cbInput uint32, dwFlags uint32) (ret uint32) {
	r0, _, _ := syscall.SyscallN(procNCryptSetProperty.Addr(), uintptr(hObject), uintptr(unsafe.Pointer(pszProperty)), uintptr(unsafe.Pointer(pbInput)), uintptr(cbInput), uintptr(dwFlags))
	ret = uint32(r0)
	return
}

func nCryptSignHash(hKey nCryptKeyHandle, pPaddingInfo *byte, pbHashValue *byte, cbHashValue uint32, pbSignature *byte, cbSignature uint32, pcbResult *uint32, dwFlags uint32) (ret uint32) {
	r0, _, _ := syscall.SyscallN(procNCryptSignHash.Addr(), uintptr(hKey), uintptr(unsafe.Pointer(pPaddingInfo)), uintptr(unsafe.Pointer(pbHashValue)), uintptr(cbHashValue), uintptr(unsafe.Pointer(pbSignature)), uintptr(cbSignature), uintptr(unsafe.Pointer(pcbResult)), uintptr(dwFlags))
	ret = uint32(r0)
	return
}
