// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {options} from '../models';
import {config} from '../models';

export function ExportCustomFilterLists():Promise<void>;

export function HardwareKeyUnavailableReason():Promise<string>;

export function ImportCustomFilterLists():Promise<void>;

export function IsNoSelfUpdate():Promise<boolean>;

export function OnSecondInstanceLaunch(arg1:options.SecondInstanceData):Promise<void>;

export function OpenLogsDirectory():Promise<void>;

export function RestartApplication():Promise<void>;

export function RunPendingRestart():Promise<void>;

export function SelectAppForRouting():Promise<string>;

export function SetCAKeyStorage(arg1:config.KeyStorageType):Promise<void>;

export function StartProxy():Promise<void>;

export function StopProxy():Promise<void>;

export function UninstallCA():Promise<void>;
