// Code generated by 'go generate'; DO NOT EDIT.

package process

import (
	"syscall"
	"unsafe"

	"golang.org/x/sys/windows"
)

var _ unsafe.Pointer

// Do the interface allocations only once for common
// Errno values.
const (
	errnoERROR_IO_PENDING = 997
)

var (
	errERROR_IO_PENDING error = syscall.Errno(errnoERROR_IO_PENDING)
	errERROR_EINVAL     error = syscall.EINVAL
)

// errnoErr returns common boxed Errno values, to prevent
// allocations at runtime.
func errnoErr(e syscall.Errno) error {
	switch e {
	case 0:
		return errERROR_EINVAL
	case errnoERROR_IO_PENDING:
		return errERROR_IO_PENDING
	}
	// TODO: add more here, after collecting data on the common
	// error values see on Windows. (perhaps when running
	// all.bat?)
	return e
}

var (
	modiphlpapi = windows.NewLazySystemDLL("iphlpapi.dll")
	modkernel32 = windows.NewLazySystemDLL("kernel32.dll")
	modversion  = windows.NewLazySystemDLL("version.dll")

	procGetExtendedTcpTable        = modiphlpapi.NewProc("GetExtendedTcpTable")
	procGetLongPathNameW           = modkernel32.NewProc("GetLongPathNameW")
	procOpenProcess                = modkernel32.NewProc("OpenProcess")
	procQueryFullProcessImageNameW = modkernel32.NewProc("QueryFullProcessImageNameW")
	procGetFileVersionInfoSizeW    = modversion.NewProc("GetFileVersionInfoSizeW")
	procGetFileVersionInfoW        = modversion.NewProc("GetFileVersionInfoW")
	procVerQueryValueW             = modversion.NewProc("VerQueryValueW")
)

func getExtendedTcpTable(pTcpTable *byte, pdwSize *uint32, bOrder bool, ulAf uint32, tableClass uint32, reserved uint32) (ret uint32) {
	var _p0 uint32
	if bOrder {
		_p0 = 1
	}
	r0, _, _ := syscall.SyscallN(procGetExtendedTcpTable.Addr(), uintptr(unsafe.Pointer(pTcpTable)), uintptr(unsafe.Pointer(pdwSize)), uintptr(_p0), uintptr(ulAf), uintptr(tableClass), uintptr(reserved))
	ret = uint32(r0)
	return
}

func getLongPathName(shortPath *uint16, longPath *uint16, longPathSize uint32) (requiredSize uint32, err error) {
	r0, _, e1 := syscall.SyscallN(procGetLongPathNameW.Addr(), uintptr(unsafe.Pointer(shortPath)), uintptr(unsafe.Pointer(longPath)), uintptr(longPathSize))
	requiredSize = uint32(r0)
	if requiredSize == 0 {
		err = errnoErr(e1)
	}
	return
}

func openProcess(desiredAccess uint32, inheritHandle bool, processId uint32) (process handle, err error) {
	var _p0 uint32
	if inheritHandle {
		_p0 = 1
	}
	r0, _, e1 := syscall.SyscallN(procOpenProcess.Addr(), uintptr(desiredAccess), uintptr(_p0), uintptr(processId))
	process = handle(r0)
	if process == 0 {
		err = errnoErr(e1)
	}
	return
}

func queryFullProcessImageName(process handle, flags uint32, buffer *uint16, bufferSize *uint32) (err error) {
	r1, _, e1 := syscall.SyscallN(procQueryFullProcessImageNameW.Addr(), uintptr(process), uintptr(flags), uintptr(unsafe.Pointer(buffer)), uintptr(unsafe.Pointer(bufferSize)))
	if r1 == 0 {
		err = errnoErr(e1)
	}
	return
}

func getFileVersionInfoSize(filename *uint16, handle *uint32) (size uint32, err error) {
	r0, _, e1 := syscall.SyscallN(procGetFileVersionInfoSizeW.Addr(), uintptr(unsafe.Pointer(filename)), uintptr(unsafe.Pointer(handle)))
	size = uint32(r0)
	if size == 0 {
		err = errnoErr(e1)
	}
	return
}

func getFileVersionInfo(filename *uint16, handle uint32, len uint32, data *byte) (err error) {
	r1, _, e1 := syscall.SyscallN(procGetFileVersionInfoW.Addr(), uintptr(unsafe.Pointer(filename)), uintptr(handle), uintptr(len), uintptr(unsafe.Pointer(data)))
	if r1 == 0 {
		err = errnoErr(e1)
	}
	return
}

func verQueryValue(block *byte, subBlock *uint16, buffer *unsafe.Pointer, len *uint32) (err error) {
	r1, _, e1 := syscall.SyscallN(procVerQueryValueW.Addr(), uintptr(unsafe.Pointer(block)), uintptr(unsafe.Pointer(subBlock)), uintptr(unsafe.Pointer(buffer)), uintptr(unsafe.Pointer(len)))
	if r1 == 0 {
		err = errnoErr(e1)
	}
	return
}
